In [1]:
import pandas as pd

In [4]:
val_eff = pd.read_csv("val_1_eff.csv", index_col=0)

In [6]:
val_rec = pd.read_csv("val_1_rec1.csv", index_col=0)

In [10]:
val_recepit_1 = val_rec.merge(val_eff, on=['orders_details_id_x', 'bigbag_number'])

In [13]:
val_recepit_1.columns = ['moisture', 'bulk_density', 'orders_details_id', 'bigbad_id', 'efficiency']

In [15]:
val_recepit_1.to_csv("val_recept_1_preds.csv")

In [20]:
val_eff_0 = pd.read_csv("recept_0_reg_pred.csv")

In [19]:
val_reg_0 = pd.read_csv("efficiency_val_receipt_0.csv")

In [24]:
val_reg_0

,Unnamed: 0,Unnamed: 0.1,orders_details_id_x,bigbag_number,bigbag_filling_time_end,sifter_speed_nominal_pct,orders_details_id_y,testing_time,steam_preasure,dd_speed,...,start,Unnamed: 0.1.1,id,particles_grp1,particles_grp2,particles_grp3,moisture,usage_pct,elems,efficiency
0,0,0,0,1,2018-04-04 13:00:00,0.69999999999999996,4,2018-04-04 12:30:00.000,7.0,9.0,...,2018-04-04 12:40:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
1,1,1,0,2,2018-04-04 14:40:00,0.69999999999999996,5,2018-04-04 14:30:00.000,7.0,9.0,...,2018-04-04 14:20:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
2,2,2,0,3,2018-04-04 15:50:00,0.69999999999999996,5,2018-04-04 15:30:00.000,7.0,9.0,...,2018-04-04 15:30:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
3,3,3,0,4,2018-04-04 17:30:00,0.69999999999999996,5,2018-04-04 16:30:00.007,7.0,9.0,...,2018-04-04 17:10:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
4,4,4,0,5,2018-04-04 19:10:00,0.69999999999999996,5,2018-04-04 18:30:00.017,7.0,9.0,...,2018-04-04 18:50:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
5,5,5,0,6,2018-04-04 20:00:00,0.69999999999999996,5,2018-04-04 19:30:00.020,7.0,9.0,...,2018-04-04 19:40:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
6,6,6,0,7,2018-04-04 21:10:00,0.69999999999999996,5,2018-04-04 20:30:00.027,7.0,9.0,...,2018-04-04 20:50:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
7,7,7,0,8,2018-04-04 22:25:00,0.69999999999999996,5,2018-04-04 21:30:00.030,7.0,9.0,...,2018-04-04 22:05:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
8,8,8,0,9,2018-04-04 23:35:00,0.69999999999999996,5,2018-04-04 23:30:00.040,7.0,9.0,...,2018-04-04 23:15:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
9,9,9,0,10,2018-04-05 00:45:00,0.69999999999999996,5,2018-04-05 00:30:00.047,7.0,9.0,...,2018-04-05 00:25:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
10,10,10,0,11,2018-04-05 02:20:00,0.69999999999999996,5,2018-04-05 01:30:00.050,7.0,9.0,...,2018-04-05 02:00:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
11,11,11,0,12,2018-04-05 03:30:00,0.69999999999999996,5,2018-04-05 02:30:00.057,6.7,9.0,...,2018-04-05 03:10:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
12,12,12,0,13,2018-04-05 04:30:00,0.69999999999999996,5,2018-04-05 03:30:00.060,6.5,9.0,...,2018-04-05 04:10:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
13,13,13,0,14,2018-04-05 05:25:00,0.69999999999999996,5,2018-04-05 04:30:00.067,6.5,9.0,...,2018-04-05 05:05:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
14,14,14,0,15,2018-04-05 06:40:00,0.69999999999999996,5,2018-04-05 06:30:00.077,6.5,9.0,...,2018-04-05 06:20:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
15,15,15,0,16,2018-04-05 07:50:00,0.80000000000000004,5,2018-04-05 07:30:00.080,6.5,9.0,...,2018-04-05 07:30:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
16,16,16,0,17,2018-04-05 09:10:00,0.80000000000000004,5,2018-04-05 08:30:00.087,6.5,9.0,...,2018-04-05 08:50:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
17,17,17,0,18,2018-04-05 10:40:00,0.80000000000000004,5,2018-04-05 10:30:00.097,6.5,9.0,...,2018-04-05 10:20:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
18,18,18,0,19,2018-04-05 11:55:00,0.80000000000000004,5,2018-04-05 11:30:00.100,6.5,9.0,...,2018-04-05 11:35:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
19,19,19,0,20,2018-04-05 13:10:00,0.80000000000000004,5,2018-04-05 12:30:00.107,6.5,9.0,...,2018-04-05 12:50:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
20,20,20,0,21,2018-04-05 14:25:00,0.80000000000000004,5,2018-04-05 13:30:00.110,6.5,9.0,...,2018-04-05 14:05:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
21,21,21,0,22,2018-04-05 16:05:00,0.80000000000000004,5,2018-04-05 14:30:00.117,6.5,9.0,...,2018-04-05 15:45:00,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,114.039439
22,22,22,2,1,2018-05-08 22:25:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,...,2018-05-08 22:05:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
23,23,23,2,2,2018-05-09 00:00:00,0.80000000000000004,12,2018-05-08 23:30:00.000,6.6,10.0,...,2018-05-08 23:40:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
24,24,24,2,3,2018-05-09 01:25:00,0.80000000000000004,12,2018-05-09 00:30:00.000,6.6,10.0,...,2018-05-09 01:05:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
25,25,25,2,4,2018-05-09 03:15:00,0.80000000000000004,12,2018-05-09 02:30:00.000,6.6,10.0,...,2018-05-09 02:55:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
26,26,26,2,5,2018-05-09 04:45:00,0.80000000000000004,12,2018-05-09 04:30:00.000,6.6,10.0,...,2018-05-09 04:25:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
27,27,27,2,6,2018-05-09 06:20:00,0.80000000000000004,12,2018-05-09 05:30:00.000,6.6,10.0,...,2018-05-09 06:00:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
28,28,28,2,7,2018-05-09 07:45:00,0.80000000000000004,12,2018-05-09 07:30:00.000,6.6,10.0,...,2018-05-09 07:25:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
29,29,29,2,8,2018-05-09 09:25:00,80-90%,12,2018-05-09 08:30:00.000,6.6,10.0,...,2018-05-09 09:05:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
30,30,30,2,9,2018-05-09 10:41:00,0.93000000000000005,12,2018-05-09 10:30:00.000,6.6,10.0,...,2018-05-09 10:21:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
31,31,31,2,10,2018-05-09 13:35:00,0.93000000000000005,12,2018-05-09 13:30:00.000,6.6,10.0,...,2018-05-09 13:15:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
32,32,32,2,11,2018-05-09 15:00:00,0.93000000000000005,12,2018-05-09 14:30:00.000,6.6,10.0,...,2018-05-09 14:40:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
33,33,33,2,17,2018-05-09 15:00:00,0.93000000000000005,12,2018-05-09 14:30:00.000,6.6,10.0,...,2018-05-09 14:40:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,116.443021
34,34,34,2,12,2018-05-09 16:10:00,0.93000000000000005,12,2018-05-09 15:30:00.000,6.6,10.5,...,2018-05-09 15:50:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,120.071826
35,35,35,2,13,2018-05-09 17:25:00,0.93000000000000005,12,2018-05-09 16:30:00.000,6.6,10.5,...,2018-05-09 17:05:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,120.071826
36,36,36,2,14,2018-05-09 18:40:00,0.93000000000000005,12,2018-05-09 18:30:00.000,6.6,11.0,...,2018-05-09 18:20:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,123.700631
37,37,37,2,15,2018-05-09 19:50:00,0.93000000000000005,12,2018-05-09 19:30:00.000,6.6,11.0,...,2018-05-09 19:30:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,123.700631
38,38,38,2,16,2018-05-09 21:10:00,0.93000000000000005,12,2018-05-09 20:30:00.000,6.6,11.0,...,2018-05-09 20:50:00,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,123.700631
39,39,39,1,9,2018-05-08 21:20:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,...,2018-05-08 21:00:00,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,121.225067
40,40,40,1,8,2018-05-08 19:55:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,...,2018-05-08 19:35:00,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,121.225067
41,41,41,1,7,2018-05-08 18:40:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,...,2018-05-08 18:20:00,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,121.225067
42,42,42,1,6,2018-05-08 17:25:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,...,2018-05-08 17:05:00,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,121.225067
43,43,43,1,4,2018-05-08 14:50:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,...,2018-05-08 14:30:00,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,121.225067
44,44,44,1,3,2018-05-08 13:25:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,...,2018-05-08 13:05:00,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,121.225067
45,45,45,1,2,2018-05-08 12:20:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,...,2018-05-08 12:00:00,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,121.225067
46,46,46,1,1,2018-05-08 10:50:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,...,2018-05-08 10:30:00,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,121.225067
47,47,47,1,5,2018-05-08 16:10:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,...,2018-05-08 15:50:00,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,121.225067
48,48,48,3,1,2018-05-09 22:45:00,0.80000000000000004,12,2018-05-09 22:30:00.000,6.6,10.0,...,2018-05-09 22:25:00,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,119.442540
49,49,49,3,2,2018-05-10 00:20:00,0.80000000000000004,12,2018-05-09 23:30:00.000,6.6,10.0,...,2018-05-10 00:00:00,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,119.442540
50,50,50,3,6,2018-05-10 06:15:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,...,2018-05-10 05:55:00,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,119.442540
51,51,51,3,5,2018-05-10 04:50:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,...,2018-05-10 04:30:00,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,119.442540
52,52,52,3,7,2018-05-10 07:30:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,...,2018-05-10 07:10:00,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,119.442540
53,53,53,3,3,2018-05-10 01:45:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,...,2018-05-10 01:25:00,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,119.442540
54,54,54,3,4,2018-05-10 03:15:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,...,2018-05-10 02:55:00,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,119.442540
55,55,55,3,8,2018-05-10 08:10:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,...,2018-05-10 07:50:00,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,119.442540

In [31]:
val_reg_0 = val_reg_0[['orders_details_id_x', 'bigbag_number', 'efficiency']]

In [28]:
val_eff_0

,Unnamed: 0,orders_details_id_x,bigbag_number,bigbag_filling_time_end,sifter_speed_nominal_pct,orders_details_id_y,testing_time,steam_preasure,dd_speed,temp_out,...,Unnamed: 0.1,id,particles_grp1,particles_grp2,particles_grp3,moisture,usage_pct,elems,moisture_pred,bulk_density_pred
0,0,0,1,2018-04-04 13:00:00,0.69999999999999996,4,2018-04-04 12:30:00.000,7.0,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
1,1,0,2,2018-04-04 14:40:00,0.69999999999999996,5,2018-04-04 14:30:00.000,7.0,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
2,2,0,3,2018-04-04 15:50:00,0.69999999999999996,5,2018-04-04 15:30:00.000,7.0,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
3,3,0,4,2018-04-04 17:30:00,0.69999999999999996,5,2018-04-04 16:30:00.007,7.0,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
4,4,0,5,2018-04-04 19:10:00,0.69999999999999996,5,2018-04-04 18:30:00.017,7.0,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
5,5,0,6,2018-04-04 20:00:00,0.69999999999999996,5,2018-04-04 19:30:00.020,7.0,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
6,6,0,7,2018-04-04 21:10:00,0.69999999999999996,5,2018-04-04 20:30:00.027,7.0,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
7,7,0,8,2018-04-04 22:25:00,0.69999999999999996,5,2018-04-04 21:30:00.030,7.0,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
8,8,0,9,2018-04-04 23:35:00,0.69999999999999996,5,2018-04-04 23:30:00.040,7.0,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
9,9,0,10,2018-04-05 00:45:00,0.69999999999999996,5,2018-04-05 00:30:00.047,7.0,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
10,10,0,11,2018-04-05 02:20:00,0.69999999999999996,5,2018-04-05 01:30:00.050,7.0,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
11,11,0,12,2018-04-05 03:30:00,0.69999999999999996,5,2018-04-05 02:30:00.057,6.7,9.0,120.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
12,12,0,13,2018-04-05 04:30:00,0.69999999999999996,5,2018-04-05 03:30:00.060,6.5,9.0,125.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
13,13,0,14,2018-04-05 05:25:00,0.69999999999999996,5,2018-04-05 04:30:00.067,6.5,9.0,125.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
14,14,0,15,2018-04-05 06:40:00,0.69999999999999996,5,2018-04-05 06:30:00.077,6.5,9.0,125.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
15,15,0,16,2018-04-05 07:50:00,0.80000000000000004,5,2018-04-05 07:30:00.080,6.5,9.0,125.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
16,16,0,17,2018-04-05 09:10:00,0.80000000000000004,5,2018-04-05 08:30:00.087,6.5,9.0,125.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
17,17,0,18,2018-04-05 10:40:00,0.80000000000000004,5,2018-04-05 10:30:00.097,6.5,9.0,125.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
18,18,0,19,2018-04-05 11:55:00,0.80000000000000004,5,2018-04-05 11:30:00.100,6.5,9.0,125.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
19,19,0,20,2018-04-05 13:10:00,0.80000000000000004,5,2018-04-05 12:30:00.107,6.5,9.0,125.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
20,20,0,21,2018-04-05 14:25:00,0.80000000000000004,5,2018-04-05 13:30:00.110,6.5,9.0,125.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
21,21,0,22,2018-04-05 16:05:00,0.80000000000000004,5,2018-04-05 14:30:00.117,6.5,9.0,125.0,...,0,0,0.789210,0.209790,0.0,11.8881,0.999,3,3.882244,213.915295
22,22,2,1,2018-05-08 22:25:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,123.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
23,23,2,2,2018-05-09 00:00:00,0.80000000000000004,12,2018-05-08 23:30:00.000,6.6,10.0,123.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
24,24,2,3,2018-05-09 01:25:00,0.80000000000000004,12,2018-05-09 00:30:00.000,6.6,10.0,123.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
25,25,2,4,2018-05-09 03:15:00,0.80000000000000004,12,2018-05-09 02:30:00.000,6.6,10.0,123.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
26,26,2,5,2018-05-09 04:45:00,0.80000000000000004,12,2018-05-09 04:30:00.000,6.6,10.0,123.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
27,27,2,6,2018-05-09 06:20:00,0.80000000000000004,12,2018-05-09 05:30:00.000,6.6,10.0,123.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
28,28,2,7,2018-05-09 07:45:00,0.80000000000000004,12,2018-05-09 07:30:00.000,6.6,10.0,124.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
29,29,2,8,2018-05-09 09:25:00,80-90%,12,2018-05-09 08:30:00.000,6.6,10.0,124.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
30,30,2,9,2018-05-09 10:41:00,0.93000000000000005,12,2018-05-09 10:30:00.000,6.6,10.0,124.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
31,31,2,10,2018-05-09 13:35:00,0.93000000000000005,12,2018-05-09 13:30:00.000,6.6,10.0,121.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
32,32,2,11,2018-05-09 15:00:00,0.93000000000000005,12,2018-05-09 14:30:00.000,6.6,10.0,121.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
33,33,2,17,2018-05-09 15:00:00,0.93000000000000005,12,2018-05-09 14:30:00.000,6.6,10.0,121.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
34,34,2,12,2018-05-09 16:10:00,0.93000000000000005,12,2018-05-09 15:30:00.000,6.6,10.5,122.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
35,35,2,13,2018-05-09 17:25:00,0.93000000000000005,12,2018-05-09 16:30:00.000,6.6,10.5,122.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
36,36,2,14,2018-05-09 18:40:00,0.93000000000000005,12,2018-05-09 18:30:00.000,6.6,11.0,122.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
37,37,2,15,2018-05-09 19:50:00,0.93000000000000005,12,2018-05-09 19:30:00.000,6.6,11.0,122.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
38,38,2,16,2018-05-09 21:10:00,0.93000000000000005,12,2018-05-09 20:30:00.000,6.6,11.0,122.0,...,2,2,0.790000,0.210000,0.0,11.8000,1.000,1,4.090298,227.897350
39,39,1,9,2018-05-08 21:20:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,123.0,...,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,4.099516,227.897350
40,40,1,8,2018-05-08 19:55:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,123.0,...,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,4.099516,227.897350
41,41,1,7,2018-05-08 18:40:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,123.0,...,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,4.099516,227.897350
42,42,1,6,2018-05-08 17:25:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,123.0,...,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,4.099516,227.897350
43,43,1,4,2018-05-08 14:50:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,123.0,...,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,4.099516,227.897350
44,44,1,3,2018-05-08 13:25:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,123.0,...,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,4.099516,227.897350
45,45,1,2,2018-05-08 12:20:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,123.0,...,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,4.099516,227.897350
46,46,1,1,2018-05-08 10:50:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,123.0,...,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,4.099516,227.897350
47,47,1,5,2018-05-08 16:10:00,0.80000000000000004,10,2018-04-25 04:30:00.000,6.5,10.0,123.0,...,1,1,0.790000,0.210000,0.0,11.8368,1.000,3,4.099516,227.897350
48,48,3,1,2018-05-09 22:45:00,0.80000000000000004,12,2018-05-09 22:30:00.000,6.6,10.0,122.0,...,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,3.806087,228.892778
49,49,3,2,2018-05-10 00:20:00,0.80000000000000004,12,2018-05-09 23:30:00.000,6.6,10.0,122.0,...,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,3.806087,228.892778
50,50,3,6,2018-05-10 06:15:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,122.0,...,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,3.806087,228.892778
51,51,3,5,2018-05-10 04:50:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,122.0,...,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,3.806087,228.892778
52,52,3,7,2018-05-10 07:30:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,122.0,...,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,3.806087,228.892778
53,53,3,3,2018-05-10 01:45:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,122.0,...,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,3.806087,228.892778
54,54,3,4,2018-05-10 03:15:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,122.0,...,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,3.806087,228.892778
55,55,3,8,2018-05-10 08:10:00,0.80000000000000004,12,2018-05-10 01:30:00.000,6.6,10.0,122.0,...,3,3,0.603775,0.396225,0.0,12.6595,1.000,2,3.806087,228.892778

In [30]:
val_eff_0 = val_eff_0[['orders_details_id_x', 'bigbag_number', 'moisture_pred', 'bulk_density_pred']]

In [33]:
df = val_reg_0.merge(val_eff_0, on=['orders_details_id_x', 'bigbag_number'])

In [34]:
df.head()

,orders_details_id_x,bigbag_number,efficiency,moisture_pred,bulk_density_pred
0,0,1,114.039439,3.882244,213.915295
1,0,2,114.039439,3.882244,213.915295
2,0,3,114.039439,3.882244,213.915295
3,0,4,114.039439,3.882244,213.915295
4,0,5,114.039439,3.882244,213.915295

In [35]:
df.columns = [ 'orders_details_id', 'bigbad_id', 'efficiency', 'moisture', 'bulk_density']

In [ ]:
df.to_csv("receipt")